const $ = s => document.querySelector(s);
const fmt = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const defaultData = {settings:{nextPayday:'2026-07-24',frequency:'biweekly',allocations:{Savings:35,'Down Payment':20,Gas:7,Insurance:9},categories:['Food','Gas','Shopping','Entertainment','Bills','Other']},paychecks:[],transactions:[],goals:[]};
let data = JSON.parse(localStorage.getItem('moneyMoves') || 'null') || defaultData;
let active = 'dashboard';
const save=()=>localStorage.setItem('moneyMoves',JSON.stringify(data));
const money=n=>fmt.format(Number(n||0)); const today=()=>new Date().toISOString().slice(0,10);
const currentPaycheck=()=>data.paychecks.at(-1);
const income=()=>currentPaycheck()?.amount||0;
const allocated=()=>currentPaycheck()?Object.values(currentPaycheck().allocations).reduce((a,b)=>a+b,0):0;
const transactionsTotal=()=>data.transactions.reduce((a,x)=>a+x.amount,0);
const goalsTotal=()=>data.goals.reduce((a,x)=>a+x.saved,0);
const available=()=>income()-allocated()-transactionsTotal()-goalsTotal();
const daysUntil=()=>Math.max(0,Math.ceil((new Date(data.settings.nextPayday+'T00:00')-new Date())/86400000));
const escape=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function activity(){return [...data.transactions.map(x=>({...x,type:'spend'})),...data.paychecks.map(x=>({name:'Paycheck',amount:x.amount,date:x.date,type:'pay'}))].sort((a,b)=>b.date.localeCompare(a.date));}
function dashboard(){const bal=available(), days=daysUntil(), daily=days?Math.max(0,bal/days):bal; const paycheck=currentPaycheck();
 $('#dashboard').innerHTML=`<div class="hero"><p class="hero-label">AVAILABLE TO SPEND</p><div class="balance ${bal<0?'negative':''}">${money(bal)}</div><p class="safe">Safe today: ${money(daily)}</p></div><div class="grid"><div class="stat"><p>Current paycheck</p><strong>${money(income())}</strong></div><div class="stat"><p>Spent</p><strong>${money(transactionsTotal())}</strong></div><div class="stat"><p>Allocated</p><strong>${money(allocated())}</strong></div><div class="stat"><p>Next payday</p><strong>${days ? days+' day'+(days===1?'':'s') : 'Today'}</strong></div></div><div class="section-title"><h2>Allocated this paycheck</h2></div><div class="allocation-list">${paycheck?Object.entries(paycheck.allocations).map(([name,amount])=>`<article class="card"><div class="row"><div><strong>${name}</strong><p>${data.settings.allocations[name]||0}% of paycheck</p></div><strong>${money(amount)}</strong></div><div class="progress"><i style="width:${data.settings.allocations[name]||0}%"></i></div></article>`).join(''):'<div class="empty">Your allocation cards will appear after you log your first paycheck.</div>'}</div><div class="section-title"><h2>Recent activity</h2><button class="link-btn" data-go="transactions">See all</button></div><div class="card activity">${activity().slice(0,4).map(item=>`<div class="activity-item"><div class="activity-icon">${item.type==='pay'?'$':'−'}</div><div class="activity-main"><strong>${escape(item.name)}</strong><p>${item.date}</p></div><strong class="${item.type==='pay'?'amount-in':'amount-out'}">${item.type==='pay'?'+':'−'}${money(item.amount)}</strong></div>`).join('')||'<div class="empty">No activity yet. Your money timeline will show up here.</div>'}</div><div class="section-title"><h2>Smart insight</h2></div><div class="insight">${!paycheck?'Log your first paycheck on payday to start tracking your money.':bal<0?'You are over your available balance. Review recent spending before making another purchase.':`You can spend about <b>${money(daily)}</b> a day and stay on track until payday.`}</div>`; }
function transactions(){const items=activity().filter(x=>x.type==='spend');$('#transactions').innerHTML=`<div class="section-title"><h2>Every purchase</h2><button class="link-btn" id="addTransaction">+ Add</button></div><div class="card activity">${items.map(x=>`<div class="activity-item"><div class="activity-icon">−</div><div class="activity-main"><strong>${escape(x.name)}</strong><p>${escape(x.category)} · ${x.date}${x.notes?' · '+escape(x.notes):''}</p></div><strong class="amount-out">−${money(x.amount)}</strong></div>`).join('')||'<div class="empty">No transactions yet.<br>Tap + to log your first purchase.</div>'}</div><button class="fab" id="addTransactionFab">+ Add transaction</button>`}
function payday(){const due=daysUntil()===0;$('#payday').innerHTML=`<div class="payday-box"><p>${due?'IT’S PAYDAY':'NEXT PAYDAY'}</p><h2>${due?'Ready to log it':new Date(data.settings.nextPayday+'T00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</h2><p>${due?'Enter your paycheck and your plan will update immediately.':`${daysUntil()} day${daysUntil()===1?'':'s'} to go`}</p><button class="primary" id="openPayday">${due?'Log paycheck':'Log early'}</button></div><div class="section-title"><h2>How it works</h2></div><div class="insight">Your paycheck is automatically divided using your settings. Once logged, the next payday advances by ${data.settings.frequency==='weekly'?'7':'14'} days.</div>`}
function goals(){ $('#goals').innerHTML=`<div class="section-title"><h2>Your goals</h2><button class="link-btn" id="addGoal">+ Add goal</button></div>${data.goals.map((g,i)=>{let p=Math.min(100,g.saved/g.target*100);return `<article class="goal-card"><div class="row"><h3>${escape(g.name)}</h3><button class="link-btn" data-deposit="${i}">Add money</button></div><p>${money(g.saved)} of ${money(g.target)}${g.date?' · target '+g.date:''}</p><div class="progress"><i style="width:${p}%"></i></div></article>`}).join('')||'<div class="empty">No goals yet.<br>Create one and move money toward something important.</div>'}`}
function settings(){const a=data.settings.allocations;$('#settings').innerHTML=`<div class="settings"><section class="card setting-group"><h3>Payday schedule</h3><div class="setting-row"><label>Next payday</label><input id="nextPayday" type="date" value="${data.settings.nextPayday}"></div><div class="setting-row"><label>Schedule</label><select id="frequency"><option value="biweekly" ${data.settings.frequency==='biweekly'?'selected':''}>Every 2 weeks</option><option value="weekly" ${data.settings.frequency==='weekly'?'selected':''}>Weekly</option></select></div></section><section class="card setting-group"><h3>Automatic allocations</h3>${Object.entries(a).map(([n,v])=>`<div class="setting-row"><label>${n}</label><input class="allocation-input" data-name="${n}" type="number" min="0" max="100" value="${v}"><span>%</span></div>`).join('')}</section><section class="card setting-group"><h3>Data</h3><div class="setting-row"><label>Stored only on this device</label><button class="link-btn" id="exportData">Export backup</button></div><div class="setting-row"><label>Remove all app data</label><button class="link-btn" id="resetData">Reset</button></div></section></div>`}
function render(){
  const screens=['dashboard','transactions','payday','goals','settings'];
  screens.forEach(id=>{
    const screen=document.getElementById(id);
    screen.classList.toggle('active',id===active);
    if(id===active) ({dashboard,transactions,payday,goals,settings})[id]();
  });
  $('.topbar h1').textContent=active[0].toUpperCase()+active.slice(1);
  document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.screen===active));
}
function openTransaction(){ $('#formTitle').textContent='Add transaction';$('#entryType').value='transaction';$('#nameLabel').firstChild.textContent='Merchant';$('#categoryLabel').hidden=false;$('#dateLabel').hidden=false;$('#notesLabel').hidden=false;$('#category').innerHTML=data.settings.categories.map(c=>`<option>${c}</option>`).join('');$('#entryDate').value=today();$('#entryForm').reset();$('#entryDate').value=today();$('#entryDialog').showModal();}
document.addEventListener('click',e=>{let t=e.target.closest('button');if(!t)return;if(t.dataset.closeDialog){document.getElementById(t.dataset.closeDialog).close();return}if(t.dataset.screen){active=t.dataset.screen;render()}if(t.id==='quickAdd'||t.id==='addTransaction'||t.id==='addTransactionFab')openTransaction();if(t.id==='openPayday'){$('#paycheckAmount').value='';preview();$('#paydayDialog').showModal()}if(t.id==='addGoal')$('#goalDialog').showModal();if(t.dataset.go){active=t.dataset.go;render()}if(t.dataset.deposit!==undefined){let amount=Number(prompt('How much do you want to move into this goal?'));if(amount>0&&amount<=available()){data.goals[Number(t.dataset.deposit)].saved+=amount;save();render()}else if(amount>available())alert('That is more than your available-to-spend balance.')}if(t.id==='resetData'&&confirm('Delete all Money Moves data from this device?')){data=JSON.parse(JSON.stringify(defaultData));save();render()}if(t.id==='exportData'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='money-moves-backup.json';a.click();URL.revokeObjectURL(a.href)}});
$('#entryForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;let amount=Number($('#amount').value);if(!amount)return;e.preventDefault();data.transactions.push({id:crypto.randomUUID(),name:$('#name').value.trim(),amount,category:$('#category').value,date:$('#entryDate').value,notes:$('#notes').value.trim()});save();$('#entryDialog').close();render()});
function preview(){let n=Number($('#paycheckAmount').value)||0;$('#allocationPreview').innerHTML=Object.entries(data.settings.allocations).map(([x,p])=>`<div><span>${x} (${p}%)</span><b>${money(n*p/100)}</b></div>`).join('')+`<div><span>Available to spend</span><b>${money(n*(100-Object.values(data.settings.allocations).reduce((a,b)=>a+b,0))/100)}</b></div>`}$('#paycheckAmount').addEventListener('input',preview);
$('#paydayForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let amount=Number($('#paycheckAmount').value);if(!amount)return;let allocations=Object.fromEntries(Object.entries(data.settings.allocations).map(([n,p])=>[n,Math.round(amount*p)/100]));data.paychecks.push({id:crypto.randomUUID(),amount,allocations,date:today()});let d=new Date(data.settings.nextPayday+'T00:00');d.setDate(d.getDate()+(data.settings.frequency==='weekly'?7:14));data.settings.nextPayday=d.toISOString().slice(0,10);save();$('#paydayDialog').close();active='dashboard';render()});
$('#goalForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();data.goals.push({id:crypto.randomUUID(),name:$('#goalName').value.trim(),target:Number($('#goalTarget').value),saved:0,date:$('#goalDate').value});save();$('#goalDialog').close();render()});
document.addEventListener('change',e=>{if(e.target.id==='nextPayday'){data.settings.nextPayday=e.target.value;save()}if(e.target.id==='frequency'){data.settings.frequency=e.target.value;save()}if(e.target.classList.contains('allocation-input')){data.settings.allocations[e.target.dataset.name]=Number(e.target.value)||0;save()}render()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');render();
